# Generated by Django 4.1 on 2022-08-14 09:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotelbookings', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_booked', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(3)])),
                ('booking_amount', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(4)])),
                ('hotel_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbookings.hotelbooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
