# Generated by Django 4.1 on 2022-08-14 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhotelbookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhotelbooking',
            name='booking_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(400)]),
        ),
        migrations.AlterField(
            model_name='userhotelbooking',
            name='rooms_booked',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
