# Generated by Django 4.1 on 2022-08-14 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=15, unique=True)),
                ('no_of_rooms', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(3)])),
                ('price_per_night', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(4)])),
                ('hotel_description', models.CharField(max_length=100)),
            ],
        ),
    ]
