# Generated by Django 4.1 on 2022-09-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hoteladdress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_name',
            new_name='name',
        ),
    ]
