# Generated by Django 4.1 on 2022-11-13 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_tour_description_tour_description_and_more'),
        ('tourimages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourimage',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_images', to='tours.tour'),
        ),
    ]
