# Generated by Django 4.1 on 2022-08-14 09:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tourbookingdates', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_participants', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(2)])),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
                ('tour_booking_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourbookingdates.tourbookingdate')),
            ],
        ),
    ]
