# Generated by Django 4.1 on 2022-09-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_activity_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_price',
            new_name='price',
        ),
    ]
