# Generated by Django 4.1 on 2022-11-24 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitybookingdays', '0002_alter_weekday_week_day'),
        ('activitybookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitybooking',
            name='activity_booking_date',
        ),
        migrations.AddField(
            model_name='activitybooking',
            name='activity_booking_day',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activitybookingdays.weekday'),
        ),
    ]
