# Generated by Django 4.1 on 2022-11-13 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_rename_activity_description_activity_description_and_more'),
        ('activityimages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityimage',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_images', to='activities.activity'),
        ),
    ]
