# Generated by Django 4.1 on 2022-08-14 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=15, unique=True)),
                ('tour_price', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(4)])),
                ('tour_description', models.CharField(max_length=100)),
                ('max_participants', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(2)])),
                ('tour_duration', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(2)])),
            ],
        ),
    ]
