# Generated by Django 4.1 on 2022-09-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_max_participants_alter_tour_tour_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='tour_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='tour_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='tour_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='tour_price',
            new_name='price',
        ),
    ]
