# Generated by Django 4.1 on 2022-09-15 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_credit_card_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_card_no',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
