# Generated by Django 4.1 on 2022-09-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
