# Generated by Django 4.1 on 2022-09-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_card_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
