# Generated by Django 4.1 on 2022-11-13 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_rename_hotel_description_hotel_description_and_more'),
        ('hotelimages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='hotels.hotel'),
        ),
    ]
